"use client";

import { motion } from "framer-motion";
import { ArrowUpRight } from "lucide-react";
import Link from "next/link";

import { MAX_YEAR, MIN_YEAR, useHistoryStore } from "@/features/history-state/history-store";

export function Hero() {
  const year = useHistoryStore((state) => state.currentYear);
  const setCurrentYear = useHistoryStore((state) => state.setCurrentYear);
  const years = Array.from({ length: MAX_YEAR - MIN_YEAR + 1 }, (_, index) => MIN_YEAR + index);
  return <section className="relative grid min-h-[82vh] content-center overflow-hidden border-b border-ink/15 py-16 lg:grid-cols-[1.15fr_0.85fr] lg:py-24"><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.65, ease: [0.22, 1, 0.36, 1] }} className="relative z-10 max-w-3xl"><p className="mb-8 text-xs tracking-[0.28em] text-cinnabar uppercase">Interactive history · 907—960</p><p className="font-serif text-[clamp(5rem,15vw,12rem)] leading-[0.72] tracking-[-0.08em] text-ink">{year}</p><h1 className="mt-10 max-w-2xl font-serif text-4xl leading-[1.18] tracking-[-0.045em] text-ink sm:text-6xl">一年之内，天下的边界为何被重新书写？</h1><p className="mt-7 max-w-xl text-base leading-8 text-muted">从一个年份出发，看清政权如何更替、人物如何选择，事件又如何推动下一次转折。</p><div className="mt-9 flex flex-wrap items-center gap-3"><label><span className="sr-only">选择探索年份</span><select aria-label="选择探索年份" value={year} onChange={(event) => setCurrentYear(Number(event.target.value))} className="h-11 rounded-full border border-ink/15 bg-paper px-5 font-serif outline-none focus:ring-2 focus:ring-cinnabar">{years.map((item) => <option key={item} value={item}>{item} 年</option>)}</select></label><Link href={`/map?year=${year}`} aria-label={`进入 ${year} 年`} className="inline-flex h-11 items-center gap-3 rounded-full bg-ink px-6 text-sm text-paper transition-colors hover:bg-cinnabar focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cinnabar focus-visible:ring-offset-2">进入 {year} 年<ArrowUpRight aria-hidden="true" className="size-4" /></Link></div></motion.div><div className="pointer-events-none relative mt-16 min-h-80 lg:mt-0"><motion.div initial={{ opacity: 0, scale: .94, rotate: -10 }} animate={{ opacity: 1, scale: 1, rotate: -7 }} transition={{ delay: .18, duration: .8 }} className="absolute inset-[8%_-12%_12%_8%] rounded-[48%_38%_55%_34%] border border-ink/35 bg-[rgba(64,105,94,0.08)]" /><div className="absolute inset-[28%_28%_26%_2%] rotate-[8deg] rounded-[45%_58%_36%_48%] border border-cinnabar/60 bg-cinnabar/5" /><div className="absolute right-[7%] top-[8%] font-serif text-8xl text-ink/[0.06]">五代</div><div className="absolute bottom-[12%] left-[17%] rounded-sm bg-cinnabar px-3 py-2 font-serif text-sm tracking-[0.25em] text-paper shadow-xl">{year === 936 ? "后晋" : "年末"}</div></div></section>;
}
