import Link from "next/link";

import { PersonPortrait } from "@/features/people/person-portrait";
import { clampSeriesYear } from "@/lib/history/series";
import { fiveDynastiesConfig } from "@/data/series/five-dynasties/config";
import type { HistorySeriesConfig } from "@/types/series";
import type { Person } from "@/types/history";

export function KeyPeople({ people, series = fiveDynastiesConfig, routePrefix = "" }: { people: Person[]; series?: HistorySeriesConfig; routePrefix?: string }) { return <section className="py-20"><div className="flex flex-col items-start justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-[10px] tracking-[0.2em] text-cinnabar uppercase">People</p><h2 className="mt-4 font-serif text-3xl sm:text-4xl">人物不是名单，是时代的转向点</h2></div><Link href={`${routePrefix}/people?year=${series.defaultYear}${series.featuredPersonId && people.some((person) => person.id === series.featuredPersonId) ? `&person=${series.featuredPersonId}` : ""}`} aria-label="探索人物关系" className="shrink-0 text-sm text-cinnabar underline underline-offset-8">探索人物关系</Link></div><div className="mt-10 grid gap-px overflow-hidden rounded-2xl border border-ink/10 bg-ink/10 sm:grid-cols-2 lg:grid-cols-4">{people.slice(0, 8).map((person, index) => <Link key={person.id} href={`${routePrefix}/people?person=${person.id}&year=${clampSeriesYear(person.deathYear ?? series.defaultYear, series)}`} className="group min-h-48 bg-paper p-5 hover:bg-white"><PersonPortrait person={person} /><div className="mt-5 flex items-baseline justify-between gap-3"><h3 className="font-serif text-xl group-hover:text-cinnabar">{person.name}</h3><span aria-hidden="true" className="font-serif text-2xl text-ink/20">{String(index + 1).padStart(2, "0")}</span></div><p className="mt-3 text-xs leading-6 text-muted">{person.summary}</p></Link>)}</div></section>; }
